[project]
name = "ds-pandas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "ipynb>=0.5.1",
    "pandas>=2.2.3",
]
